CC/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
	url(r'^core/', include('core.urls')),
    url(r'^admin/', admin.site.urls),
]

core/urls.py
from django.conf.urls import url
from . import views
from core.views import list_evidence_view, create_evidence_view, list_submissions_view

app_name = 'core'
urlpatterns = [
    # ex: /core/
    url(r'^$', views.index, name='index'),
    url(r'^(?P<corecomp_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^submitted', views.submitted, name='submitted'),
	url(r'^evidence_form/$', create_evidence_view, name='evidence'),
	url(r'^CES/$', list_evidence_view, name='CES'),
    url(r'^submissions/$', list_submissions_view, name='submissions')
]

core/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.forms import ModelForm
from django import forms


# Teachers or admin create a list of "I can statements" for each core competency
class CoreComp(models.Model):
    CORE_COMP = (
        ('CT', 'Critical Thinking'),
        ('CR', 'Creative Thinking'),
        ('SR', 'Social Responsibility'),
        ('CO', 'Communication'),
        ('PA', 'Personal Awareness'),
        ('CI', 'Cultural Identity'),
    )
    iCan = models.CharField(max_length=100)
    core_comp = models.CharField(max_length=2, choices=CORE_COMP)

    def __str__(self):
        return self.get_core_comp_display() + ':' + ' ' + self.iCan


# Teachers or admin enter course details and curriculum Big Ideas
class BigIdeaRubric(models.Model):
    COURSE_NAME = (
        ('MA', 'Mathematics'),
        ('AR', 'Arts Eduction'),
        ('EN', 'English Language Arts'),
        ('SC', 'Science'),
        ('SS', 'Social Studies'),
    )
    GRADE_LEVEL = (
        (8, '8'),
        (9, '9'),
    )
    gradeLevel = models.IntegerField(choices=GRADE_LEVEL, default=8)
    courseName = models.CharField(max_length=2, choices=COURSE_NAME)
    bigIdea = models.CharField(max_length=200)

    def __str__(self):
        return self.get_courseName_display() + ':' + ' ' + self.bigIdea


# Students can self-enrol their own details
class Student(models.Model):
    emailaddy = models.CharField(max_length=50)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    SIN = models.IntegerField(default=1)

    def __str__(self):
        return self.last_name


# This is the self-assessment. Students choose grade, course, "I can" statement
# Students write a description of their artifact, and the significance of their artifact in relation to the CC
class Evidence(models.Model):
    corecomp = models.ForeignKey(CoreComp, on_delete=models.CASCADE)
    bigidearubric = models.ForeignKey(BigIdeaRubric, on_delete=models.CASCADE)
    #	student = models.ForeignKey(Student, on_delete=models.CASCADE)
    pkcore = models.IntegerField(default=1)
    pkidea = models.IntegerField(default=1)
    done = models.BooleanField(default=True)
    artifact = models.CharField(max_length=200)
    signif = models.CharField(max_length=200)
    dateAdded = models.DateTimeField('date added', blank=True)

def __str__(self):
    return self.artifact


class EvidenceForm(ModelForm):
    class Meta:
        model = Evidence
        fields = ['bigidearubric', 'corecomp', 'artifact', 'signif']

# class Question(models.Model):
#     question_text = models.CharField(max_length=200)
#     pub_date = models.DateTimeField('date published')
#
#
# class Choice(models.Model):
#     question = models.ForeignKey(Question, on_delete=models.CASCADE)
#     choice_text = models.CharField(max_length=200)
#     votes = models.IntegerField(default=0)

core/forms.py
from django import forms
from .models import BigIdeaRubric, CoreComp, Evidence, Student

class CESForm(forms.Form):
    subject = forms.ModelChoiceField(queryset=BigIdeaRubric.objects.values('courseName'))
    icanstatement = forms.ModelChoiceField(queryset=CoreComp.objects.values('iCan'))

core/views.py
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import get_object_or_404, Http404, render
from django.forms import ModelForm
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.utils import timezone
from django.core.urlresolvers import reverse_lazy, reverse
from django.core.exceptions import ObjectDoesNotExist

from .models import CoreComp, BigIdeaRubric, EvidenceForm, Student, Evidence


def index(request):
    core_comp_list = CoreComp.objects.order_by('id')[:5]
    context = {'core_comp_list': core_comp_list}
    return render(request, 'core/index.html', context)


def detail(request, corecomp_id):
    corecomp = get_object_or_404(CoreComp, pk=corecomp_id)
    return render(request, 'core/detail.html', {'corecomp': corecomp})


def results(request, evidence_id):
    response = "You're looking at the results of evidence %s."
    return HttpResponse(response % evidence_id)


def submitted(request):
    return render(request, 'core/submitted.html')
#    return HttpResponse("Thank you for submitting your evidence.")


class EvidenceCreateView(CreateView):
    model = Evidence
    form_class = EvidenceForm
    template = "create_evidence.html"

    def form_valid(self, form):
        evidence = form.save(commit=False)
        evidence.dateAdded = timezone.now()
        evidence.save()
        return super(EvidenceCreateView, self).form_valid(form)
    def get_success_url(self):
        return reverse('core:submitted')

create_evidence_view = EvidenceCreateView.as_view()

# this view gives the overall picture/grid of the student's core competencies
class EvidenceListView(ListView):
    model = Evidence
    template_name = 'core/evidence_list.html'

    def get_context_data(self, **kwargs):
        context = super(EvidenceListView, self).get_context_data(**kwargs)
        # order the core competencies by groupings as expected in curriculum
        corecomps_ordered = CoreComp.objects.order_by('core_comp', '-iCan')
        corecomps = corecomps_ordered
        context['corecomps'] = corecomps
        # order the big ideas by subject area
        bigidea_ordered = BigIdeaRubric.objects.order_by('courseName','bigIdea')
        bigideas = bigidea_ordered
        context['bigideas'] = bigideas
        evidences = Evidence.objects.all()
        # pkcore and pkbig will be used to match artifact with table cell
        # pkcore and pkbig correspond to the id of each corecompetency and bigidea
        for ev in evidences:
            ev.pkcore = ev.corecomp.pk
            ev.pkidea = ev.bigidearubric.pk
            ev.save()
        # create a list that is ordered for the corecompetencies and bigideas
        grid = []
        for big in bigideas:
            grid.append(big.bigIdea)
            for cor in corecomps:
                grid.append((cor.pk,big.pk))
        # get length of corecomps and bigideas so we can match evidence with grid
        length_core = len(CoreComp.objects.all())
        length_row = length_core + 1
        length_big = len(BigIdeaRubric.objects.all())
        # create a list that will identify if evidence has been giving for each individual cell
        tableGrid = []
        n = 0
        for big in bigideas:
            tableGrid.append(big.bigIdea)
            # every rox begins with the bigIdea, not the evidence. Skip this first column in each row
            if n%(length_core+1) ==0:
                n += 1
            for l in range(length_core):
                pkc = grid[n][0]
                pkb = grid[n][1]
                n += 1
                # check to see if there is evidence given for the table cell
                a = evidences.filter(pkcore=pkc, pkidea=pkb).count()
                if a == 0:
                    print(a)
                    tableGrid.append('No')
                else:
                    print(a)
                    tableGrid.append('Yes')

        # context['artifacts'] = Evidence.objects.values('artifact')
        # context['signifs'] = Evidence.objects.values('signif')
        # context['length_core'] = length_core
        # context['length_big'] = length_big
        context['length_row'] = length_row
        context['tableGrid'] = tableGrid
        context['evidences'] = evidences
        context['grid'] = grid
        return context

list_evidence_view = EvidenceListView.as_view()

# this view shows a student's list of artifacts and statements of significance
class SubmissionsListView(ListView):
    model = Evidence
    template_name = 'core/submissions_list.html'

    def get_context_data(self, **kwargs):
        context = super(SubmissionsListView, self).get_context_data(**kwargs)
        # order the core competencies by groupings as expected in curriculum
        corecomps_ordered = CoreComp.objects.order_by('core_comp', '-iCan')
        corecomps = corecomps_ordered
        context['corecomps'] = corecomps
        # order the big ideas by subject area
        bigidea_ordered = BigIdeaRubric.objects.order_by('courseName','bigIdea')
        bigideas = bigidea_ordered
        context['bigideas'] = bigideas
        evidences = Evidence.objects.all()
        context['artifacts'] = Evidence.objects.values('artifact')
        context['evidences'] = evidences
        return context

list_submissions_view = SubmissionsListView.as_view()

core/templates/core/Evidence_form.html
<!-- <h1>{{ corecomp.iCan }}</h1>
<ul>
{% for Bigidearubric in BigIdeaRubric.all %}
    <li>{{ bigIdea.Bigidearubric.choice_text }}</li>
{% endfor %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
</ul> -->


<!-- {% if bigidearubric_list %}
	<form action="{% url 'core:submitted' %}" method="post">

	{% csrf_token %}

		<select>
			<option>{{ bigidearubric_list.gradeLevel }}</option>
		</select>
	</form>
{% endif %} -->
<form action="{% url 'core:evidence' %}" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="submit" />
</form>

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
{% block head %}<head>{% load static %}

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>CES - {% block body_block %}Claim, Evidence, Significance{% endblock %}</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans|Lato|Droid+Serif|Volkhov:400italic|Droid+Sans' rel='stylesheet' type='text/css'>

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href="{% static "css/normalize.css" %}">
  <link rel="stylesheet" href="{% static "css/skeleton.css" %}">
  <link rel="stylesheet" href="{% static "css/layout.css" %}">
<!-- Favicons
	================================================== -->
<!--	<link rel="shortcut icon" href="images/favicon.ico">
	<link rel="apple-touch-icon" href="images/apple-touch-icon.png">
	<link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">-->

</head>
{% endblock %}
<body>


  <!-- Primary Page Layout
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  {% block header %}
  <div class="band header">
    <div class="container">
      <div class="row">
			<div class="twelve columns">
				<img src="{% static "images/header1.png" %}">
				<span class="righttext">The 2017/18 Edition</span>
				<hr />
			</div>
      </div><!-- row -->
    </div><!-- container -->
  </div><!-- band header -->
  {% endblock %}
  {% block body %}{% endblock %}

<!-- End Document
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
</body>
</html>

core/templates/core/detail.html
<h1>{{ corecomp.iCan }}</h1>
<ul>
{% for Bigidearubric in BigIdeaRubric.all %}
    <li>{{ bigIdea.Bigidearubric.choice_text }}</li>
{% endfor %}
</ul>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

core/templates/core/evidence_detail.html
{% extends 'core/base.html' %}


{% block body %}
<div class="container">
    <div class="row">
        <div class="twelve columns">
            <h1>Submitted Evidences</h1>
        </div>
    </div>
    <div class="row">
        <ul>
            {% for ev in evidences %}
            <li>{{ ev.artifact }}</li>
            {% endfor %}
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        </ul>
    </div>

</div>
{% endblock %}

core/templates/core/evidence_list.html
{% extends 'core/base.html' %}


{% block body %}
<div class="container">
    <div class="row">
        <div class="twelve columns">
            <h1>Submitted Evidences</h1>
        </div>
    </div>
    <div class="row">
        <table>
            <tr>
                <th>Big Ideas</th>
                {% for comps in corecomps %}
                    <th class="rotate"><div><span>{{ comps.iCan }}</span></div></th>
                {% endfor %}
            </tr>
            {% for item in tableGrid %}
                {% if forloop.counter0|divisibleby:length_row %}<tr>{% endif %}
                <td>{{ item }}</td>
                {% if forloop.counter|divisibleby:length_row %}</tr>{% endif %}
            {% endfor %}
        </table>
        <!-- <ul>
            {% for evidence in object_list %}
            <li>{{ evidence.artifact }}</li>
            {% endfor %}
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        </ul> -->
    </div>

</div>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}
{% block body %}
<div class = "container">
    <div class="row">
        <div class = "twelve colums">
            <h1>CES: Claim, Evidence, Significance</h1>
        </div>
    </div>
    <div class="row">
        <div class = "twelve colums">
            <p>Tracking your progress with core competencies.</p>
        </div>
    </div>
    <div class="row">
        <div class="one-third column"><a href ="{% url 'core:evidence' %}" class="button" style="color:#999999">CLICK HERE TO SUBMIT EVIDENCE</a></div>
        <div class="one-third column"><a href ="{% url 'core:CES' %}" class="button" style="color:#999999">CLICK HERE TO SEE COMPETENCY GRID</a></div>
        <div class="one-third column"><a href ="{% url 'core:submissions' %}" class="button" style="color:#999999">CLICK HERE TO SEE SUBMISSIONS</a></div>
    </div>
</div>
{% endblock %}

<!--{% if core_comp_list %}
    <ul>
    {% for corecomp in core_comp_list %}
        <li><a href="{% url 'core:detail' corecomp.id %}">{{ corecomp.iCan }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}-->

core/templates/core/student_form.html
<!-- <h1>{{ corecomp.iCan }}</h1>
<ul>
{% for Bigidearubric in BigIdeaRubric.all %}
    <li>{{ bigIdea.Bigidearubric.choice_text }}</li>
{% endfor %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
</ul> -->


<!-- {% if bigidearubric_list %}
	<form action="{% url 'core:submitted' %}" method="post">

	{% csrf_token %}

		<select>
			<option>{{ bigidearubric_list.gradeLevel }}</option>
		</select>
	</form>
{% endif %} -->

{{ form.as_p }}

core/templates/core/submissions_list.html
{% extends 'core/base.html' %}


{% block body %}
<div class="container">
    <div class="row">
        <div class="twelve columns">
            <h1>Submissions</h1>
        </div>
    </div>
    <div class="row">
        <ul>
            {% for ev in evidences %}
            <li>{{ ev.artifact }}</li>
            <ul>
                <li>{{ ev.signif }}</li>
            </ul>
            {% endfor %}
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        </ul>
    </div>

</div>
{% endblock %}

core/templates/core/submitted.html
{% extends 'core/base.html' %}
{% block body %}
<div class = "container">
    <div class = "twelve colums">
        <h1>Thank you for your submission</h1>
    </div>
    <div class="row">
        <div class="one-half column"><a href ="{% url 'core:evidence' %}" class="button" style="color:#999999">CLICK HERE TO SUBMIT EVIDENCE</a></div>
        <div class="one-half column"><a href ="{% url 'core:CES' %}" class="button" style="color:#999999">CLICK HERE TO SEE SUBMISSIONS</a></div>
    </div>
</div>
{% endblock %}