CC/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
	url(r'^core/', include('core.urls')),
    url(r'^admin/', admin.site.urls),
]

classroom/urls.py
from django.conf.urls import url
from . import views
from classroom.views import create_classroom_view, delete_block_view, randomize

app_name = "classroom"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^submitted', views.submitted, name='submitted'),
	url(r'^classup/$', create_classroom_view, name='classroom'),
    url(r'^block/$', views.block, name='block'),
    # url(r'^(?P<pk>[0-9]+)/deleteblock/$', delete_block_view, name='deleteblock'),
    url(r'^(?P<pk>[0-9]+)/deleteblock/$', delete_block_view, name='deleteblock'),
    url(r'^adjust/$', views.adjust, name='adjust'),
    url(r'^random/$', views.block, name='random'),
]

classroom/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.forms import ModelForm
from django import forms
import django_filters

class Classroom(models.Model):
    COURSE_NAME = (
        ('MA8', 'Math 8'),
        ('SC10', 'Science 10'),
        ('PH11', 'Physics 11'),
        ('PH12', 'Physics 12'),
    )
    BLOCK_NUMBER = (
        ('11', 'Block 1-1'),
        ('12', 'Block 1-2'),
        ('13', 'Block 1-3'),
        ('14', 'Block 1-4'),
        ('21', 'Block 2-1'),
        ('22', 'Block 2-2'),
        ('23', 'Block 2-3'),
        ('24', 'Block 2-4'),
    )
    class_list = models.TextField()
    course_name = models.CharField(max_length=20, choices=COURSE_NAME)
    course_block = models.CharField(max_length=10, choices=BLOCK_NUMBER)
    group_size = models.IntegerField(default=3)

    def __str__(self):
        return self.get_course_block_display()

    def save(self, *args, **kwargs):
        super(Classroom, self).save(*args, **kwargs)
        # overrides the default save function to parse the class list
        studentList = []
        studentList = self.class_list.split('\n')
        print (studentList)
        for line in studentList:
            line = line.strip('\r')
            s = Student.objects.create(nickname = line, classroom = self)

class Student(models.Model):
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    student_first = models.CharField(default='John', max_length=30)
    student_last = models.CharField(default='Smith', max_length=30)
    nickname = models.CharField(default='JohnS', max_length=31)
    attend = models.BooleanField(default=True)

class ClassroomForm(ModelForm):
    class Meta:
        model = Classroom
        fields = ['course_name', 'course_block','class_list']

    def clean(self):
        try:
            Classroom.objects.get(course_block=self.cleaned_data['course_block'])
            self.redirect = True
            raise forms.ValidationError("Exists already")
        except Classroom.DoesNotExist:
            pass
        return self.cleaned_data

class DeleteForm(ModelForm):
    class Meta:
        model = Classroom
        fields = ['course_block']

class StudentFilter(django_filters.FilterSet):
    class Meta:
        model = Student
        fields = ['classroom__course_block']




# class AttendForm(ModelForm):
#     class Meta:
#         model = Classroom
#         fields = ['course_block']
#
#     def __init__(self, *args, **kwargs):
#         super(AttendForm, self).__init__(*args, **kwargs)

# class RandomForm(ModelForm):
#     class Meta:
#         model = Student
#         fields = ['nickname', 'attend']

classroom/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader, Context
from django.shortcuts import get_object_or_404, Http404, render, get_list_or_404
from django.forms import ModelForm
from django.views.generic.edit import CreateView, FormView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.core import serializers
import json

from .models import Classroom, Student, ClassroomForm, StudentFilter, DeleteForm
# from .models import RandomForm, AttendForm


def index(request):
    nickname_list = Classroom.objects.order_by('nickname')
    context = {'nickname_list': nickname_list}
    return render(request, 'classroom/index.html', context)

def submitted(request):
    return render(request, 'classroom/submitted.html')

class ClassroomCreateView(CreateView):
    model = Classroom
    form_class = ClassroomForm

    def get_success_url(self):
        return reverse('classroom:block')

create_classroom_view = ClassroomCreateView.as_view()

class BlockDeleteView(DeleteView):
    model = Classroom
    slug_field = 'id'
    success_url = ('classroom/classup')
    template_name = 'classroom/delete.html'

delete_block_view = BlockDeleteView.as_view()

def adjust(request):
    classroom = Classroom.objects.all().first()
    if request.method == 'POST':
        form = DeleteForm(request.POST)
        if form.is_valid():
            return render(request, 'classroom/adjust.html', {'form':form,'classroom':classroom})
    else:
        form = DeleteForm()

    return render(request, 'classroom/adjust.html', {'form': form,'classroom': classroom})

def randomize(request):
    classblock = request.GET.get('class_block')
    students = Student.objects.all().filter(classroom__course_block=classblock)
    print (classblock)
    print (Student.objects.filter(classroom__course_block=classblock))
    return render(request, 'classroom/block_list.html', {'students': students})

def block(request):
    classroom = Classroom.objects.all().order_by('course_block')
    classblock = request.GET.get('class_block')
    cblock = Classroom.objects.all().filter(course_block=classblock)
    cblocknum = cblock.count()
    students = Student.objects.all().filter(classroom__course_block=classblock)
    nicknames = [s.nickname for s in students]
    student_names = json.dumps(list(nicknames))
    context = {'students': students}
    context['classroom'] = classroom
    context['cblock'] = cblock
    context['student_names'] = student_names
    context['cblocknum'] = cblocknum
    # context['cblock'] = cblock
    # context['cblocknum'] = cblocknum
    template = loader.get_template('classroom/block_list.html')
    # context ={ 'classroom' : classroom, }
    print (student_names)

    # return render(request, 'classroom/block_list.html', {'classroom': classroom, 'cblock': cblock, 'cblocknum': cblocknum, 'students': students})
    return render(request, 'classroom/block_list.html', context)

def student_list(request):
    s = StudentFilter(request.GET, queryset=Student.objects.all())
    # f = AttendFilter(request.GET, queryset=Student.objects.all())
    return render(request, 'classroom/student_list.html', {'filter': s})
    # return render(request, 'classroom/student_list.html', {'filter2': f})

# class AttendFormView(FormView):
#     model = Classroom
#     form_class = AttendForm
#     template_name = 'classroom/attend_form.html'
#
#     def form_valid(self, form):
#         return super(AttendFormView, self).form_valid(form)
#
#     def get_success_url(self):
#         # return reverse('classroom:random', kwargs={'pk': self.kwargs['pk']})
#         return reverse('classroom:random', kwargs={'pk': self.kwargs['pk']})
# form_attendance_view = AttendFormView.as_view()

class ClassroomDetailView(DetailView):
    model = Classroom
    template_name = 'classroom/random_list.html'

    def get_context_data(self, **kwargs):
        class_pk = self.kwargs['pk']
        context = super(ClassroomDetailView, self).get_context_data(**kwargs)
        students = Student.objects.filter(pk = 'class_pk')
        context['students'] = students
        return context

detail_classroom_view = ClassroomDetailView.as_view()

classroom/templates/classroom/adjust.html
{% extends 'classroom/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="twelve columns">
            <h1>Delete Block</h1>
        </div>
    </div>

    <div class="row">
        <div class="twelve columns">
            <form action="{% url 'classroom:deleteblock' classroom.id %}" method="post">
	            {% csrf_token %}
                {{ classroom }}
                {{ form }}
		    <input type="submit" value="submit" />
            </form>
        </div>
    </div>

</div>
{% endblock %}

classroom/templates/classroom/attend_form.html
TESTt
<form action="{% url 'classroom:students' %}" method="post">
	{% csrf_token %}
        <select name="namedrop">
            {% for room in
        </select>
		<input type="submit" value="submit" />
</form>

classroom/templates/classroom/base.html
<!DOCTYPE html>
<html lang="en">
<head>{% load static %}

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>CES - {% block body_block %}Claim, Evidence, Significance{% endblock %}</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href="http://fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans|Lato|Droid+Serif|Volkhov:400italic|Droid+Sans' rel='stylesheet' type='text/css'>

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href="{% static "css/normalize.css" %}">
  <link rel="stylesheet" href="{% static "css/skeleton.css" %}">
  <link rel="stylesheet" href="{% static "css/layout.css" %}">
  
  <!-- JAVASCRIPT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <script type="text/javascript" language="Javascript" src="http://ajax.aspnetcdn.com/ajax/jquery/jquery-1.11.3.min.js"></script> 
  
  
<!-- Favicons
	================================================== -->
<!--	<link rel="shortcut icon" href="images/favicon.ico">
	<link rel="apple-touch-icon" href="images/apple-touch-icon.png">
	<link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">-->
    {% block extra_css %}{% endblock extra_css %}

</head>
<body>


  <!-- Primary Page Layout
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  {% block header %}
  <div class="band header">
    <div class="container">
      <div class="row">
			<div class="twelve columns">
				<img src="{% static "images/header1.png" %}">
				<span class="righttext">The 2017/18 Edition</span>
				<hr />
			</div>
      </div><!-- row -->
    </div><!-- container -->
  </div><!-- band header -->
  {% endblock %}
  {% block body %}{% endblock body %}
  {% block extra_js %}{% endblock extra_js %}

<!-- End Document
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
</body>
</html>

classroom/templates/classroom/block_list.html
{% extends 'classroom/base.html' %}


{% block body %}
<div class="container">
    <div class="row">
        <div class="two columns">
            <div id="djangorandom">
            {{ classroom.id }}
            <form action="{% url 'classroom:random' %}" method="get">
                {% csrf_token %}
                    <select name="class_block">
                        {% for room in classroom %}
                            <option value={{ room.course_block }}>{{ room.get_course_block_display }}</option>
                        {% endfor %}
                    </select>
                <span><input type="submit" value="submit" /></span>
            </form>
            </div>
        </div>
        <div class="ten columns">
                <button id="go">&raquo; Run</button>
                <button id="stop">&raquo; Stop</button>
        </div>
    </div>


</div>
{% endblock body %}
<div>
{% block extra_js %}
            <script>
                var nameArray = {{ student_names | safe }}
                console.log(nameArray);
                var numberStudents = nameArray.length;
                var interval;
                var loopAllowed = false;

                var vertGap = 30;

                var divChoice = document.createElement('div');
                divChoice.id = "choicename";
                divChoice.style.position = "absolute";
                divChoice.style.top = "570px";
                divChoice.style.left  = "500px";
                divChoice.innerHTML = " ";
                document.body.appendChild(divChoice);

                var setNames = function() {
                    var h = 0;
                    for(var n = 0; n < numberStudents; n++){
                        var extraW = 0;
                        var w = 0;
                        var divName = "floatName" + n;
                        var names = nameArray[n];
                        var divTag = document.createElement('div');
                        divTag.id = divName;
                        divTag.innerHTML = names;
                        divTag.style.position = "absolute";
                        if (n < 16) {
                            w = 0;
                            divTag.style.top = (200 + n * vertGap) + "px";
                        } else {
                            w = 120;
                            divTag.style.top = (200 + h * vertGap) + "px";
                            h++;
                        };
                        divTag.style.left  = (50 + w) + "px";
                        divTag.className = "randomFloat";
                        document.body.appendChild(divTag);
                        };
                    };
                setNames();
                $( "#go" ).click(function() {
                    console.log("it's go time");
                    var cleanDiv = document.getElementById("choicename");
                    cleanDiv.remove();
                    loopAllowed = true;
                    var max = 2;
                    var loop = function(){
                      for(var i = 0; i < (numberStudents + 1); i++){
                        var divName = "floatName" + i;
                        $( "#" + divName ).animate({
                            left: (Math.random()*500+150) + "px",
                            top: (Math.random()*350 + 350) + "px"
                        }, 300, i === max - 1 && loopAllowed ? loop : undefined);
                      }
                     };
                     loop();
                    });

                $( "#stop" ).click(function() {
                    loopAllowed = false;
                    choosePerson(0, numberStudents);
                    setTimeout(clearDivs, 2000);

                });

                var clearDivs = function() {
                    for(var i = 0; i < (numberStudents); i++) {
                        divn = "floatName" + i;
                        var elem = document.getElementById(divn);
                        elem.remove();
                        };
                    setNames();
                    };

                function choosePerson (min, max) {
                    min = Math.ceil(min);
                    max = Math.floor(max);
                    var rn = Math.floor(Math.random() * (max - min)) + min;
                    console.log(rn);



                    divChoice.innerHTML = nameArray[rn];
                    document.body.appendChild(divChoice);

                    };

            </script>
</div>
{% endblock extra_js %}

classroom/templates/classroom/classroom_form.html
{% extends 'classroom/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="twelve columns">
            <h1>Class/Block Entry</h1>
        </div>
    </div>
    <div class="row">
        <div class="one-third columns">
            <form action="{% url 'classroom:classroom' %}" method="post">
	            {% csrf_token %}
	            {{ form.as_p }}
	            <input type="submit" value="submit" />
            </form>
        </div>
    </div>
    <div class="one-third column"><a href ="{% url 'classroom:adjust' %}" class="button" style="color:#999999">CLICK HERE TO DELETE A BLOCK</a>
    </div>

</div>
{% endblock %}

classroom/templates/classroom/classroom_list.html
{% extends 'core/base.html' %}


{% block body %}
<div class="container">
    <div class="row">
        <div class="twelve columns">
            <h1>Student List</h1>
        </div>
    </div>
    <div class="row">
        <table>
            <tr>
                <th>Big Ideas</th>
                {% for comps in corecomps %}
                    <th class="rotate"><div><span>{{ comps.iCan }}</span></div></th>
                {% endfor %}
            </tr>
            {% for item in tableGrid %}
                {% if forloop.counter0|divisibleby:length_row %}<tr>{% endif %}
                <td>{{ item }}</td>
                {% if forloop.counter|divisibleby:length_row %}</tr>{% endif %}
            {% endfor %}
        </table>
        <!-- <ul>
            {% for evidence in object_list %}
            <li>{{ evidence.artifact }}</li>
            {% endfor %}
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        </ul> -->
    </div>

</div>
{% endblock %}

classroom/templates/classroom/deleteblock.html
{% extends 'classroom/base.html' %}


{% block body %}
<div class="container">
    <div class="row">
        <div class="twelve columns">
            <h1>Delete List</h1>
        </div>
    </div>
    <div class="row">
        <div class="one-third columns">
            <form action="" method="get">
	            {{ filter.form.as_p }}
	            <input type="submit" value="submit" />
            </form>
            <ul>
                {% for obj in filter.qs %}
                <li>{{ obj.nickname }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>

</div>
{% endblock %}

classroom/templates/classroom/index.html
{% extends 'classroom/base.html' %}
{% block body %}
<div class = "container">
    <div class="row">
        <div class = "twelve colums">
            <h1>Classroom List and Randomizer</h1>
        </div>
    </div>
    <div class="row">
        <div class = "twelve colums">
            <p>Tracking your progress with core competencies.</p>
        </div>
    </div>
    <div class="row">
        <div class="one-half column"><a href ="{% url 'classroom:classroom' %}" class="button" style="color:#999999">CLICK HERE TO UPLOAD CLASS LIST</a></div>
        <div class="one-half column"><a href ="{% url 'classroom:students' %}" class="button" style="color:#999999">CLICK HERE TO PICK A NAME</a></div>
    </div>
</div>
{% endblock %}

classroom/templates/classroom/randomize.html
{% extends 'classroom/base.html' %}


{% block body %}
<div class="container">
    <div class="row">
        <div class="twelve columns">
            <h1>Student Listt</h1>
        </div>
    </div>
    <div class="row">
        <div class="one-third columns">
            {% for s in students %}
            <ul>
                <li>{{ s.nickname }}</li>
            </ul>
            {% endfor %}
        </div>
    </div>

</div>
{% endblock %}

classroom/templates/classroom/student_list.html
{% extends 'classroom/base.html' %}


{% block body %}
<div class="container">
    <div class="row">
        <div class="twelve columns">
            <h1>Student List</h1>
        </div>
    </div>
    <div class="row">
        <div class="one-third columns">
            <form action="" method="get">
	            {{ filter.form.as_p }}
	            <input type="submit" value="submit" />
            </form>
            <ul>
                {% for obj in filter.qs %}
                <li>{{ obj.nickname }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>

</div>
{% endblock %}